Not pass some warnings as errors.
Some parameters are used inside ifdefs:

hardware/qcom/camera/QCamera2/HAL/QCameraMem.cpp:1557:9: error: unused variable 'i' [-Werror,-Wunused-variable]
    int i;
        ^
hardware/qcom/camera/QCamera2/HAL/QCameraMem.cpp:1615:55: error: unused parameter 'data' [-Werror,-Wunused-parameter]
int QCameraVideoMemory::closeNativeHandle(const void *data, bool metadata)
                                                      ^
hardware/qcom/camera/QCamera2/HAL/QCameraMem.cpp:1615:66: error: unused parameter 'metadata' [-Werror,-Wunused-parameter]
int QCameraVideoMemory::closeNativeHandle(const void *data, bool metadata)
                                                                 ^
3 errors generated.